### ISSUE TITLE
App doesn't show news feed

### ISSUE THREAD

**Issue by drewstephensdesigns** [laramartin/android_newsfeed#1]
I rebuilt this app following your code, however, when I launched on my device it just shows a blank screen with the color scheme.  Is there something I'm missing?

**Comment by laramartin** [comment]
Hi, thanks for your question. I updated the readme file now. 
You need an API key from The Guardian API. Then go to the class `QueryUtils`, find the `createStringUrl()` method and replace the query parameter value "test" for your API key.
